#spring:
#  cloud:
#    gateway:
#      server:
#        webmvc:
#          routes:
#            - id: user-service
#              uri: http://localhost:8081/api/v1
#              predicates:
#                - Path = /com/example/**
#server:
#  port: 8086
#  forward-headers-strategy: framework

server:
  port: 8086  # Порт Gateway

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/**
#              filters:
#                - RewritePath=/api/v1/(?<segment>.*), /api/v1/$\{segment}
              filters:
                - name: CircuitBreaker
                  args:
                    name: userCircuitBreaker
                    fallbackUri: forward:/fallback/users
                - RemoveRequestHeader=Cookie

resilience4j:
  circuitbreaker:
    instances:
      userCircuitBreaker:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

