spring:
  datasource:
    url: jdbc:postgresql://localhost:13000/userservicedb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: "identity-service"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9898