spring:
  application:
    name: user-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://localhost:8888

logging:
  level:
    org.springframework.cloud.config: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


#
#eureka:
#  client:
#    service-url
#      defaultZone=http://localhost:8761/eureka/
