server:
  port: 8081

spring:
  application:
    name=user-service: "user-service"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: alpha
  api-docs:
    path: /api-docs