server:
  port: 8081

spring:
  application:
    name=user-service: user-service

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:13000/userservicedb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: alpha
  api-docs:
    path: /api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true