server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:./config/, file:../config/, classpath:/config/
      name: config-server

spring.profiles.active: native